-- CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE namerecords (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  gender TEXT NOT NULL,
  era TEXT NOT NULL,
  recent TEXT
);
